const userActionTypes = {
  FORM_SIGN_UP_START: "FORM_SIGN_UP_START",
  FORM_SIGN_UP_SUCCESS: "FORM_SIGN_UP_SUCCESS",
  FORM_SIGN_UP_FAILURE: "FORM_SIGN_UP_FAILURE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",
  SIGN_USER_OUT_START: "SIGN_USER_OUT_START",
  SIGN_USER_OUT_SUCCESS: "SIGN_USER_OUT_SUCCESS",
  SIGN_USER_OUT_FAILURE: "SIGN_USER_OUT_FAILURE",
  CHECK_USER_SESSION_START: "CHECK_USER_SESSION_START",
  CHECK_USER_SESSION_SUCCESS: "CHECK_USER_SESSION_SUCCESS",
  CHECK_USER_SESSION_FAILURE: "CHECK_USER_SESSION_FAILURE"
};

export default userActionTypes;
